from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
import os
from api.routes import projects

app = FastAPI(
    title="AI Shorts Repurposing API",
    description="Backend for the AI Shorts Repurposing Tool",
    version="1.0.0"
)

# Ensure temp directory exists
if not os.path.exists("temp"):
    os.makedirs("temp")

print(f"--- Starting Application on port: {os.getenv('PORT', '8000')} ---")

# Mount statically to serve actual video clips generated by the system
app.mount("/temp", StaticFiles(directory="temp"), name="temp")

# Standard CORS setup to allow Next.js frontend to communicate
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Update this in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(projects.router, prefix="/api/v1/projects", tags=["Projects"])

@app.get("/health")
async def health_check():
    return {"status": "healthy", "message": "API is running!"}
